# .github/workflows/opentofu-destroy.yml
name: OpenTofu Destroy

# ─── Trigger: manual “Run workflow” button ──────────────────────────────────────
on:
  workflow_dispatch:
    inputs:
      environment:
        description: Environment to destroy
        required: true
        default: stage
        type: choice
        options: [stage, prod]

# ─── Jobs ───────────────────────────────────────────────────────────────────────
jobs:
  destroy:
    # Optional extra guard (redundant but harmless)
    if: github.event_name == 'workflow_dispatch'

    runs-on: ubuntu-latest

    # Hook into GitHub Environments so you get the approval gate
    environment:
      name: ${{ inputs.environment }}

    steps:
    - uses: actions/checkout@v4

    - name: Setup OpenTofu
      uses: opentofu/setup-opentofu@v1
      with:
        tofu_version: 1.9.0

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id:     ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-west-1

    - name: tofu init
      run: tofu init -reconfigure

    # Show a destroy plan first (great for the approval step)
    - name: tofu plan (destroy mode)
      run: |
        tofu plan \
          -destroy \
          -var="environment=${{ inputs.environment }}" \
          -out=tfplan-destroy
        tofu show tfplan-destroy

    # GitHub pauses here if the environment requires approval
    - name: tofu destroy
      run: |
        echo "About to destroy resources in environment: ${{ inputs.environment }}"
        tofu destroy \
          -auto-approve \
          -var="environment=${{ inputs.environment }}"
